const mongoose = require('mongoose');

const flashcardSchema = new mongoose.Schema({
  front: String,
  back: String,
  chapterId: { type: mongoose.Schema.Types.ObjectId, ref: 'Chapter' },
  concept: String,
  language: String,
  isAutoGenerated: Boolean,
  aiModel: String,
  createdAt: Date
});

module.exports = mongoose.model('Flashcard', flashcardSchema);